import './styles.css';
import * as pdfjsLib from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { PDFDocument } from 'pdf-lib';
pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl;

const app=document.querySelector('#app');
app.innerHTML=`<header><div><b>🧽 PDF EXAM CLEANER</b><span>100% Local</span></div><div id="meta">ยังไม่ได้เปิดไฟล์</div></header><main><aside><button id="open">📂 Open PDF</button><input id="file" type="file" accept="application/pdf" hidden><div id="drop">ลาก & วาง PDF ที่นี่</div><div class="pages" id="pages"></div></aside><section><div class="toolbar"><button id="detect">🔍 Detect</button><button id="clean">🧽 Clean</button><button id="undo">↶ Reset</button><button id="export">⬇ Export PDF</button><label>Brush <input id="size" type="range" min="5" max="80" value="25"></label><button id="eraser">🧹 Eraser</button><button id="brush">🖌 Brush</button></div><div id="status"></div><div class="viewer"><div class="canvasbox"><canvas id="original"></canvas><canvas id="work"></canvas><canvas id="mask"></canvas></div></div></section><aside class="settings"><h3>Cleaning</h3><label>Mode<select id="mode"><option value="auto">AUTO CLEAN</option><option value="color">COLOR CLEAN</option><option value="manual">MANUAL MASK</option></select></label><label>Threshold <input id="threshold" type="range" min="120" max="245" value="205"></label><p>PDF และภาพทั้งหมดประมวลผลใน Browser ไม่อัปโหลดไปยัง Server</p></aside></main>`;

const $=s=>document.querySelector(s);let pdf=null,bytes=null,pages=[],current=0,tool='brush',brush=25,dirty=false;
const canv={o:$('#original'),w:$('#work'),m:$('#mask')};
function status(t){$('#status').textContent=t}
function fitCanvases(w,h){for(const c of Object.values(canv)){c.width=w;c.height=h}}
function draw(data,canvas){canvas.getContext('2d').putImageData(data,0,0)}
function pageImage(i){return pages[i]?.cleaned||pages[i]?.original}
async function render(i){current=i;const p=pages[i];fitCanvases(p.original.width,p.original.height);draw(p.original,canv.o);draw(pageImage(i),canv.w);canv.m.getContext('2d').clearRect(0,0,canv.m.width,canv.m.height);$('#pages').querySelectorAll('.page').forEach((x,j)=>x.classList.toggle('active',j===i));dirty=!!p.cleaned}
function maskOverlay(mask,w,h){const d=new ImageData(w,h);for(let i=0;i<mask.length;i++)if(mask[i]){d.data[i*4]=255;d.data[i*4+1]=80;d.data[i*4+2]=60;d.data[i*4+3]=90}return d}
function applyMask(mask){const p=pages[current],src=p.original,out=new Uint8ClampedArray(src.data);const w=src.width,h=src.height,r=7;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(mask[y*w+x]){let R=0,G=0,B=0,n=0;for(let yy=Math.max(0,y-r);yy<=Math.min(h-1,y+r);yy+=2)for(let xx=Math.max(0,x-r);xx<=Math.min(w-1,x+r);xx+=2)if(!mask[yy*w+xx]){const q=(yy*w+xx)*4;R+=src.data[q];G+=src.data[q+1];B+=src.data[q+2];n++}const q=(y*w+x)*4;if(n){out[q]=R/n;out[q+1]=G/n;out[q+2]=B/n}out[q+3]=255}return new ImageData(out,w,h)}
function detect(){const p=pages[current],d=p.original.data,w=p.original.width,h=p.original.height,m=new Uint8Array(w*h),thr=+$('threshold').value;let n=0;for(let i=0;i<w*h;i++){const q=i*4,r=d[q],g=d[q+1],b=d[q+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);const mark=$('mode').value==='color'?mx-mn>25:mx<thr||mx-mn>30;if(mark){m[i]=1;n++}}p.mask=m;draw(maskOverlay(m,w,h),canv.m);status(`Detect: ${n.toLocaleString()} pixels flagged`)}
function clean(){const p=pages[current];if(!p.mask)detect();p.cleaned=applyMask(p.mask);draw(p.cleaned,canv.w);dirty=true;status('Cleaned — ตรวจสอบ Before/After ก่อน Export')}
function paint(e){if(tool==='none'||!pages[current])return;const r=canv.m.getBoundingClientRect(),x=Math.round((e.clientX-r.left)*canv.m.width/r.width),y=Math.round((e.clientY-r.top)*canv.m.height/r.height),rad=Math.max(1,Math.round(brush*canv.m.width/r.width/2)),p=pages[current];if(!p.mask)p.mask=new Uint8Array(p.original.width*p.original.height);for(let yy=y-rad;yy<=y+rad;yy++)for(let xx=x-rad;xx<=x+rad;xx++)if(xx>=0&&yy>=0&&xx<p.original.width&&yy<p.original.height&&(xx-x)**2+(yy-y)**2<=rad*rad)p.mask[yy*p.original.width+xx]=tool==='eraser'?0:1;draw(maskOverlay(p.mask,p.original.width,p.original.height),canv.m);dirty=true}
canv.m.addEventListener('pointerdown',e=>{canv.m.setPointerCapture(e.pointerId);paint(e)});canv.m.addEventListener('pointermove',e=>{if(e.buttons)paint(e)});
$('#open').onclick=()=>$('#file').click();$('#file').onchange=e=>e.target.files[0]&&openFile(e.target.files[0]);$('#drop').ondragover=e=>e.preventDefault();$('#drop').ondrop=e=>{e.preventDefault();e.dataTransfer.files[0]&&openFile(e.dataTransfer.files[0])};
async function openFile(file){status('Loading PDF…');bytes=new Uint8Array(await file.arrayBuffer());pdf=await pdfjsLib.getDocument({data:bytes}).promise;pages=[];for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i),v=pg.getViewport({scale:1}),scale=200/72,v2=pg.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v2.width);c.height=Math.ceil(v2.height);await pg.render({canvasContext:c.getContext('2d'),viewport:v2}).promise;pages.push({original:c.getContext('2d').getImageData(0,0,c.width,c.height),widthPt:v.width,heightPt:v.height})}$('#meta').textContent=`${file.name} · ${file.size/1048576<10?(file.size/1048576).toFixed(2):Math.round(file.size/1048576)} MB · ${pages.length} หน้า`;const list=$('#pages');list.innerHTML='';pages.forEach((p,i)=>{const d=document.createElement('div');d.className='page';const c=document.createElement('canvas');c.width=120;c.height=Math.round(120*p.original.height/p.original.width);c.getContext('2d').putImageData(p.original,0,0);d.append(c,document.createTextNode(`Page ${i+1}`));d.onclick=()=>render(i);list.append(d)});await render(0);status('พร้อมใช้งาน')}
$('#detect').onclick=detect;$('#clean').onclick=clean;$('#undo').onclick=async()=>{pages[current].cleaned=null;pages[current].mask=null;await render(current);status('คืนค่าหน้าปัจจุบันแล้ว')};$('#size').oninput=e=>brush=+e.target.value;$('#brush').onclick=()=>tool='brush';$('#eraser').onclick=()=>tool='eraser';
$('#export').onclick=async()=>{if(!pdf)return;status('กำลังสร้าง PDF…');const out=await PDFDocument.create();for(let i=0;i<pages.length;i++){const p=pages[i],d=p.cleaned||p.original,c=document.createElement('canvas');c.width=d.width;c.height=d.height;c.getContext('2d').putImageData(d,0,0);const img=await out.embedPng(c.toDataURL('image/png'));const pg=out.addPage([p.widthPt,p.heightPt]);pg.drawImage(img,{x:0,y:0,width:p.widthPt,height:p.heightPt})}const blob=new Blob([await out.save()],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pdf-cleaned.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('Export เสร็จแล้ว')};
